Description: |
  Tempalte to host static site
    - code commit repo
    - pipeline to publish it into S3 
    - creates a cloudfront distribution

Parameters:
  ProjectName:
    Type: String
  PageIndex:
    Type: String
    ConstraintDescription: "[A-Za-z0-9]+.[A-Za-z]{2-4}"
    Description: "For example index.html or index.php"

Resources: 
  S3BucketHosting:
    Type: "AWS::S3::Bucket"

  S3BucketCodeCommit:
    Type: "AWS::S3::Bucket"
    
  CodeCommitRepository:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryName: !Ref ProjectName

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Name: !Ref ProjectName
      Source:
        BuildSpec: !Sub |
                    version: 0.2
                    
                    phases:
                      build:
                        commands:
                            - aws s3 rm --recursive "s3://${S3BucketHosting}/"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts:
        EncryptionDisabled: false
        Name: !Ref CodeCommitRepository
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache:
        Type: "NO_CACHE"
      Environment: 
          ComputeType: "BUILD_GENERAL1_SMALL"
          Image: "aws/codebuild/amazonlinux2-aarch64-standard:1.0"
          ImagePullCredentialsType: "CODEBUILD"
          PrivilegedMode: false
          Type: "ARM_CONTAINER"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/${IAMRoleForCodeBuild}"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig: 
          CloudWatchLogs: 
              Status: "ENABLED"
          S3Logs: 
              Status: "DISABLED"
              EncryptionDisabled: false
      Visibility: "PRIVATE"

  IAMRoleForCodeBuild:
    Type: "AWS::IAM::Role"
    Properties:
        Path: "/service-role/"
        AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codebuild.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
        MaxSessionDuration: 3600
        ManagedPolicyArns: 
          - !Ref IAMManagedPolicyCodeBuild

  IAMManagedPolicyCodeBuild:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
        Path: "/service-role/"
        PolicyDocument: !Sub |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Resource": [
                            "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${S3BucketHosting}",
                            "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${S3BucketHosting}:*"
                        ],
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Resource": [
                            "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                        ],
                        "Action": [
                            "s3:PutObject",
                            "s3:GetObject",
                            "s3:GetObjectVersion",
                            "s3:GetBucketAcl",
                            "s3:GetBucketLocation"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Resource": [
                            "arn:aws:s3:::${S3BucketCodeCommit}",
                            "arn:aws:s3:::${S3BucketCodeCommit}/*"
                        ],
                        "Action": [
                            "s3:PutObject",
                            "s3:GetBucketAcl",
                            "s3:GetBucketLocation"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "codebuild:CreateReportGroup",
                            "codebuild:CreateReport",
                            "codebuild:UpdateReport",
                            "codebuild:BatchPutTestCases",
                            "codebuild:BatchPutCodeCoverages"
                        ],
                        "Resource": [
                            "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${S3BucketHosting}-*"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Resource": [
                            "arn:aws:s3:::${S3BucketHosting}/*",
                            "arn:aws:s3:::${S3BucketHosting}"
                        ],
                        "Action": [
                            "s3:*"
                        ]
                    }
                ]
            }

  CloudFrontDistribution:
      Type: "AWS::CloudFront::Distribution"
      Properties:
          DistributionConfig: 
              Origins: 
                - 
                  ConnectionAttempts: 3
                  ConnectionTimeout: 10
                  DomainName: !Sub "${S3BucketHosting}.s3.${AWS::Region}.amazonaws.com"
                  Id: !Sub "${S3BucketHosting}.s3.${AWS::Region}.amazonaws.com"
                  OriginPath: ""
                  S3OriginConfig: 
                      OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontCloudFrontOriginAccessIdentity}"
              OriginGroups: 
                  Quantity: 0
              DefaultCacheBehavior: 
                  AllowedMethods: 
                    - "HEAD"
                    - "GET"
                  CachedMethods: 
                    - "HEAD"
                    - "GET"
                  Compress: true
                  CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
                  SmoothStreaming: false
                  TargetOriginId: !Sub "${S3BucketHosting}.s3.${AWS::Region}.amazonaws.com"
                  ViewerProtocolPolicy: "redirect-to-https"
              Comment: ""
              PriceClass: "PriceClass_All"
              Enabled: true
              ViewerCertificate:                   
                  CloudFrontDefaultCertificate: true
              Restrictions: 
                  GeoRestriction: 
                      RestrictionType: "none"
              HttpVersion: "http2"
              DefaultRootObject: "index.html"
              IPV6Enabled: true

  CloudFrontCloudFrontOriginAccessIdentity:
      Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
      Properties:
          CloudFrontOriginAccessIdentityConfig: 
              Comment: !Sub "access-identity-${S3BucketHosting}.s3.${AWS::Region}.amazonaws.com"

Outputs:
  WebPageURL:
    Description: "URL of the page"
    Value: !GetAtt CloudFrontDistribution.DomainName
  RepositoryCloneURL:
    Description: "URL for HTTP Clone"
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp

# TODO:
# Pipeline + role
# lambda role? 
# trigger for pipeline
# Unify S3 for CodeCommit + clean it up - nested stack for this and lambda?
# Condition + If to create cloudfront with domain and certificate